Repository mobilecoinofficial/full-service, pull requests merged in 2023-02, with the labels that each got.

#687 Brian/updating rocket setup
  full-service/src/bin/main.rs
  full-service/src/json_rpc/wallet.rs
  mirror/src/public/main.rs
Labels: bug, refactor

#693 Only query for network block info a single time when getting account status
  full-service/src/service/balance.rs
Labels: refactor

#688 Add endpoint to get details of Public Address B58
  docs/v2/api-endpoints/get_address_details.md
  full-service/src/json_rpc/v1/api/wallet.rs
  full-service/src/json_rpc/v2/api/request.rs
  full-service/src/json_rpc/v2/api/response.rs
  full-service/src/json_rpc/v2/api/wallet.rs
  full-service/src/json_rpc/v2/e2e_tests/account/account_address.rs
  full-service/src/json_rpc/v2/e2e_tests/account/account_other.rs
  full-service/src/json_rpc/v2/models/mod.rs
  full-service/src/json_rpc/v2/models/public_address.rs
  full-service/src/service/address.rs
  full-service/src/service/transaction.rs
Labels: enhancement

#708 Adding watcher-db param docs [Finishes #184421396]
  README.md
Labels: documentation
