Repository mobilecoinofficial/full-service, pull requests merged in 2023-01, with the labels that each got.

#642 fixing incorrect docs for v2 get_transaction_log(s)
  docs/v2/api-endpoints/get_transaction_log.md
  docs/v2/api-endpoints/get_transaction_logs.md
  docs/v2/transactions/transaction-log/README.md
Labels: documentation

#631 Feature/upgrade rocket to v0.5
  .github/workflows/ci.yml
  Cargo.lock
  full-service/Cargo.toml
  full-service/src/bin/main.rs
  full-service/src/db/wallet_db_error.rs
  full-service/src/json_rpc/json_rpc_response.rs
  full-service/src/json_rpc/v1/api/test_utils.rs
  full-service/src/json_rpc/v1/api/wallet.rs
  full-service/src/json_rpc/v1/e2e_tests/account/account_address.rs
  full-service/src/json_rpc/v1/e2e_tests/account/account_balance.rs
  full-service/src/json_rpc/v1/e2e_tests/account/account_other.rs
  full-service/src/json_rpc/v1/e2e_tests/account/create_import/account_crud.rs
  full-service/src/json_rpc/v1/e2e_tests/account/create_import/import_account.rs
  full-service/src/json_rpc/v1/e2e_tests/gift_codes.rs
  full-service/src/json_rpc/v1/e2e_tests/other.rs
  full-service/src/json_rpc/v1/e2e_tests/transaction/build_submit/build_and_submit.rs
  full-service/src/json_rpc/v1/e2e_tests/transaction/build_submit/build_then_submit.rs
  full-service/src/json_rpc/v1/e2e_tests/transaction/build_submit/large_transaction.rs
  full-service/src/json_rpc/v1/e2e_tests/transaction/build_submit/multiple_outlay.rs
  full-service/src/json_rpc/v1/e2e_tests/transaction/transaction_other.rs
  full-service/src/json_rpc/v1/e2e_tests/transaction/transaction_txo.rs
  full-service/src/json_rpc/v1/models/txo.rs
  full-service/src/json_rpc/v2/api/test_utils.rs
  full-service/src/json_rpc/v2/api/wallet.rs
  full-service/src/json_rpc/v2/e2e_tests/account/account_address.rs
  full-service/src/json_rpc/v2/e2e_tests/account/account_balance.rs
  full-service/src/json_rpc/v2/e2e_tests/account/account_other.rs
  full-service/src/json_rpc/v2/e2e_tests/account/create_import/account_crud.rs
  full-service/src/json_rpc/v2/e2e_tests/account/create_import/import_account.rs
  full-service/src/json_rpc/v2/e2e_tests/account/create_import/view_account_flow.rs
  full-service/src/json_rpc/v2/e2e_tests/other.rs
  full-service/src/json_rpc/v2/e2e_tests/transaction/build_submit/build_and_submit.rs
  full-service/src/json_rpc/v2/e2e_tests/transaction/build_submit/build_then_submit.rs
  full-service/src/json_rpc/v2/e2e_tests/transaction/build_submit/build_unsigned.rs
  full-service/src/json_rpc/v2/e2e_tests/transaction/build_submit/large_transaction.rs
  full-service/src/json_rpc/v2/e2e_tests/transaction/build_submit/multiple_outlay.rs
  full-service/src/json_rpc/v2/e2e_tests/transaction/transaction_other.rs
  full-service/src/json_rpc/v2/e2e_tests/transaction/transaction_txo.rs
  full-service/src/json_rpc/wallet.rs
  full-service/src/lib.rs
  full-service/src/service/gift_code.rs
  full-service/src/test_utils.rs
  mirror/Cargo.toml
  mirror/src/public/main.rs
Labels: dependencies

#644 removing account syncing requiring regenerating subaddress keys
  full-service/migrations/2023-01-20-231044_add_index_to_subaddress_spend_key/down.sql
  full-service/migrations/2023-01-20-231044_add_index_to_subaddress_spend_key/up.sql
  full-service/src/db/txo.rs
  full-service/src/service/sync.rs
  full-service/src/test_utils.rs
Labels: refactor

#673 Resurrect full-service command-line interface.
  python/OLD_README.md
  python/README.md
  python/bin/mob
  python/mobilecoin/__init__.py
  python/mobilecoin/cli.py
  python/mobilecoin/client.py
  python/mobilecoin/util/__init__.py
  python/mobilecoin/util/external_pb2.py
  python/mobilecoin/util/printable_pb2.py
  python/mobilecoin/util/setup.py
  python/poetry.lock
  python/pyproject.toml
  python/tests/__init__.py
  python/tests/client_tests.py
  python/tests/stress.py
  python/tests/sync_benchmark.py
  python/tests/test_display.py
Labels: enhancement

#682 Add watcher information to v2 responses that include block information
  Cargo.lock
  full-service/Cargo.toml
  full-service/src/bin/main.rs
  full-service/src/config.rs
  full-service/src/json_rpc/v1/api/test_utils.rs
  full-service/src/json_rpc/v2/api/response.rs
  full-service/src/json_rpc/v2/api/test_utils.rs
  full-service/src/json_rpc/v2/api/wallet.rs
  full-service/src/json_rpc/v2/e2e_tests/other.rs
  full-service/src/json_rpc/v2/models/block.rs
  full-service/src/json_rpc/v2/models/ledger.rs
  full-service/src/json_rpc/v2/models/mod.rs
  full-service/src/json_rpc/v2/models/watcher.rs
  full-service/src/service/ledger.rs
  full-service/src/service/mod.rs
  full-service/src/service/models/ledger.rs
  full-service/src/service/models/mod.rs
  full-service/src/service/models/watcher.rs
  full-service/src/service/wallet_service.rs
  full-service/src/service/watcher.rs
  full-service/src/test_utils.rs
Labels: block explorer
